### ISSUE TITLE
Slow loading files when only uploading .txt file

### ISSUE THREAD

**Issue by kawilliams** [alex-r-bigelow/traveler-integrated#10]
Uploading a single text file took a long time and threw this error:

```
Saving katetree shelf: meta
Saving katetree shelf: primitives
Saving katetree shelf: primitiveLinks
Saving katetree pickle: trees
INFO: ('127.0.0.1', 49386) - "POST /datasets/katetree HTTP/1.1" 201
INFO: ('127.0.0.1', 49386) - "POST /datasets/katetree/log HTTP/1.1" 200
ERROR: Exception in ASGI application
Traceback (most recent call last):
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 370, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/starlette/applications.py", line 133, in call
await self.error_middleware(scope, receive, send)
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/starlette/middleware/errors.py", line 122, in call
raise exc from None
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/starlette/middleware/errors.py", line 100, in call
await self.app(scope, receive, _send)
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/starlette/exceptions.py", line 73, in call
raise exc from None
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/starlette/exceptions.py", line 62, in call
await self.app(scope, receive, sender)
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/starlette/routing.py", line 585, in call
await route(scope, receive, send)
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/starlette/routing.py", line 207, in call
await self.app(scope, receive, send)
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/starlette/routing.py", line 43, in app
await response(scope, receive, send)
File "/Users/katywilliams/GitHub/traveler-integrated/env/lib/python3.6/site-packages/starlette/responses.py", line 197, in call
async for chunk in self.body_iterator:
File "/Users/katywilliams/GitHub/traveler-integrated/clientLogger.py", line 16, in iterate
await startProcess()
File "./serve.py", line 111, in startProcess
await db.save(label, logger)
File "/Users/katywilliams/GitHub/traveler-integrated/database.py", line 128, in save
await log('Saving %s shelf: %s' % (label, stype))
TypeError: 'ClientLogger' object is not callable
```

**Comment by alex-r-bigelow** [comment]
Should be fixed per #11; closing for now
